name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  args:  # id of input
    description: 'arguments to the action'
    required: true
    default: '{}'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'
